universes:
  equity_active_direct:
    description: Equity, Active, Direct, investible, growth (current hard-coded universe).
    asset_types:
    - Equity
    include_categories: []
    exclude_categories: []
    only_direct: true
    only_active: true
    investible_only: true
    growth_only: true
  test preset:
    description: ''
    asset_types:
    - Equity
    - Debt
    - Hybrid
    - Other
    include_categories: []
    exclude_categories: []
    only_direct: true
    only_active: true
    investible_only: false
    growth_only: true
